# Generated by Django 5.2.1 on 2026-05-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_scored_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Challenge description, e.g. "Predict runs in this over"')),
                ('type', models.CharField(choices=[('runs', 'Runs in over'), ('wickets', 'Wickets'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lock_at', models.DateTimeField(help_text='Predictions close at this time')),
                ('is_locked', models.BooleanField(default=False)),
                ('correct_outcome', models.CharField(blank=True, help_text='Admin fills this after the event. Triggers scoring.', max_length=100, null=True)),
                ('scored', models.BooleanField(default=False)),
                ('n8n_notified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.predictionroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_value', models.CharField(help_text='e.g. "12" or "2 wickets"', max_length=100)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('exact', 'Exact match'), ('close', 'Close guess'), ('incorrect', 'Incorrect')], default='pending', max_length=10)),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
