# Generated by Django 5.2.1 on 2026-05-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement_dynamicprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room this match belongs to. Leave blank for global matches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.predictionroom'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='correct_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='lock_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dynamicprediction',
            name='prediction_value',
            field=models.CharField(max_length=100),
        ),
    ]
